### PR TITLE
Update events page

### LINKED ISSUE #91: Add current events (as of 20161106) to the Events page
# Natural Language Processing Education With Pizza
Featuring Dr. Stan Szpakowicz, Emeritus Professor at the University of Ottawa

Tuesday 8 November 2016, 19:00-20:00 in Old Main 1792
[https://trucspizza.eventbrite.ca](https://trucspizza.eventbrite.ca)

# How cognitive computing is changing business models
Featuring Caroline Ong of IBM Global Business Services Part of the Business Kickstart Speaker Series.
Thursday 10 November 2016, 8:00-9:30 in the Mountain Room at the Campus Activity Center. [http://generator.sites.tru.ca/event/business-kickstart-speaker-series-caroline-ong/](http://generator.sites.tru.ca/event/business-kickstart-speaker-series-caroline-ong/)

# Bowling night
Friday 2 December 2016, 19:30 at Bowler Time (North Shore)
_More details and reservations to follow_

### PR DESCRIPTION
**Pull request by mitchhentges**
Will fix #91

### CODE REVIEW

**Comment by frogcrush** [comment]
Some of the events are now passed.

**Comment by mitchhentges** [comment]
Should be good now

**Comment by frogcrush** [comment]
There appears to be a weird space here:
https://waa.ai/jycx.png
Otherwise A+

**Comment by frogcrush** [comment]
+1

**Comment by marcolussetti** [comment]
:+1:  from me as well.
Code looks good.
Testing in major browser looks good.

**Pull request merged**
