### PR TITLE
Fixes #54, #55

### LINKED ISSUE #54: Thomas is still in list (Mitch is a skrub)
GG

### PR DESCRIPTION
**Pull request by mitchhentges**

### CODE REVIEW

**Comment by chrisfosterelli** [comment]
Thomas is still on the board...?

**Comment by mitchhentges** [comment]
Hold on a second, was in full-doing, let me review for a sec

**Comment by mitchhentges** [comment]
Fixed. Don't have an explanation, other than being mixed up. Sorry for the confusion

**Comment by chrisfosterelli** [comment]
No worries, thanks for the fix!

**Pull request merged**
