### PR TITLE
Add /labsurvey redirect, fixes #95

### LINKED ISSUE #95: Make trucsclub.ca/labsurvey direct to Support Lab Survey

### PR DESCRIPTION
**Pull request by mitchhentges**

### CODE REVIEW

**Comment by frogcrush** [comment]
I'd suggest having a link in the body as well, just in case. Otherwise looks good.

**Comment by mitchhentges** [comment]
Good point, fixed

**Comment by frogcrush** [comment]
OK by me

**Comment by marcolussetti** [comment]
:+1: from me too.

Code looks good (only other way to do redirects on Github Pages is via Jekyll it seems).
Testing shows no issues either on major browsers.

**Pull request merged**
