### PR TITLE
Move Chad to Previous Board Members section

### PR DESCRIPTION
**Pull request by chrisfosterelli**

### CODE REVIEW

**Comment by chrisfosterelli** [comment]
@mitchhentges Merge whenever you get a sec?

**Comment by chadfawcett** [comment]
You guys can also remove me from the Guthub organization admins so I no longer have merge privileges.

**Comment by chrisfosterelli** [comment]
Yup, that should already be done!
You'll still be registered as 'watching' this repo unless you turn it off,
however.

**Comment by mitchhentges** [comment]
:+1:

**Pull request merged**
